export type Category = "painting" | "drawing";

export type Artwork = {
  slug: string;
  number: number;
  image: string;
  title: { en: string; da: string };
  medium: { en: string; da: string };
  year: string | null;
  dimensions: string | null;
  available: boolean;
  orientation: "portrait" | "landscape" | "square";
  category: Category;
};

export const artworks: Artwork[] = [
  {
    slug: "contemplation",
    number: 1,
    image: "/art/01-contemplation.jpg",
    title: { en: "Contemplation", da: "Kontemplation" },
    medium: { en: "Ink on paper", da: "Blæk på papir" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "portrait",
    category: "drawing",
  },
  {
    slug: "autoportrait-with-hat",
    number: 2,
    image: "/art/02-autoportrait-with-hat.jpg",
    title: { en: "Autoportrait with Hat", da: "Selvportræt med hat" },
    medium: { en: "Oil on linen", da: "Olie på lærred" },
    year: "2024",
    dimensions: null,
    available: true,
    orientation: "portrait",
    category: "painting",
  },
  {
    slug: "ginger-jar-moose-skull",
    number: 3,
    image: "/art/03-ginger-jar-moose-skull.jpg",
    title: {
      en: "Ginger Jar with Moose Skull",
      da: "Ingefærkrukke med elsdyrekranium",
    },
    medium: { en: "Oil on linen", da: "Olie på lærred" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "landscape",
    category: "painting",
  },
  {
    slug: "storm-coming",
    number: 4,
    image: "/art/04-storm-coming.jpg",
    title: { en: "Storm Coming", da: "Storm i vente" },
    medium: { en: "Oil on linen", da: "Olie på lærred" },
    year: "2024",
    dimensions: null,
    available: true,
    orientation: "landscape",
    category: "painting",
  },
  {
    slug: "midnight-with-trees",
    number: 5,
    image: "/art/05-midnight-with-trees.jpg",
    title: { en: "Midnight with Trees", da: "Midnat med træer" },
    medium: { en: "Oil on oak", da: "Olie på eg" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "portrait",
    category: "painting",
  },
  {
    slug: "filip",
    number: 6,
    image: "/art/06-filip.jpg",
    title: { en: "Filip", da: "Filip" },
    medium: { en: "Oil on oak", da: "Olie på eg" },
    year: "2026",
    dimensions: null,
    available: true,
    orientation: "portrait",
    category: "painting",
  },
  {
    slug: "shell-on-grey",
    number: 7,
    image: "/art/07-shell-grey-background.jpg",
    title: {
      en: "Shell on Grey Background",
      da: "Musling på grå baggrund",
    },
    medium: { en: "Ink wash on paper", da: "Blæklavering på papir" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "square",
    category: "drawing",
  },
  {
    slug: "memories-of-autumn",
    number: 8,
    image: "/art/08-memories-of-autumn.jpg",
    title: { en: "Memories of Autumn", da: "Efterårserindringer" },
    medium: { en: "Oil on linen", da: "Olie på lærred" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "landscape",
    category: "painting",
  },
  {
    slug: "twisted-willow",
    number: 9,
    image: "/art/09-twisted-willow.jpg",
    title: { en: "The Twisted Willow", da: "Den forvredne pil" },
    medium: { en: "Oil on linen", da: "Olie på lærred" },
    year: "2024/25",
    dimensions: null,
    available: true,
    orientation: "portrait",
    category: "painting",
  },
  {
    slug: "bright-sun",
    number: 10,
    image: "/art/10-bright-sun.jpg",
    title: { en: "Bright Sun", da: "Skarp sol" },
    medium: { en: "Oil on canvas", da: "Olie på lærred" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "landscape",
    category: "painting",
  },
  {
    slug: "autoportrait-with-red-cap",
    number: 11,
    image: "/art/11-autoportrait-red-cap.jpg",
    title: {
      en: "Self-Portrait with Red Cap and Palette",
      da: "Selvportræt med rød hue og palet",
    },
    medium: { en: "Oil on linen", da: "Olie på lærred" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "portrait",
    category: "painting",
  },
  {
    slug: "vanitas",
    number: 12,
    image: "/art/12-vanitas.jpg",
    title: { en: "Vanitas", da: "Vanitas" },
    medium: { en: "Oil on linen", da: "Olie på lærred" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "portrait",
    category: "painting",
  },
  {
    slug: "apples-and-pomegranate",
    number: 13,
    image: "/art/13-apples-pomegranate.jpg",
    title: {
      en: "Apples and Pomegranate",
      da: "Æbler og granatæble",
    },
    medium: { en: "Oil on linen", da: "Olie på lærred" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "landscape",
    category: "painting",
  },
  {
    slug: "still-life-with-roman-bowl",
    number: 14,
    image: "/art/14-still-life-roman-bowl.jpg",
    title: {
      en: "Still Life with Roman Bowl",
      da: "Stilleben med romersk krukke",
    },
    medium: { en: "Oil on linen", da: "Olie på lærred" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "landscape",
    category: "painting",
  },
  {
    slug: "night-landscape",
    number: 15,
    image: "/art/15-night-landscape.jpg",
    title: { en: "Night Landscape", da: "Nattelandskab" },
    medium: { en: "Oil on panel", da: "Olie på plade" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "landscape",
    category: "painting",
  },
  {
    slug: "trees-at-dusk",
    number: 16,
    image: "/art/16-trees-at-dusk.jpg",
    title: { en: "Trees at Dusk", da: "Træer i skumring" },
    medium: { en: "Oil on panel", da: "Olie på plade" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "landscape",
    category: "painting",
  },
  {
    slug: "summer-meadow",
    number: 17,
    image: "/art/17-summer-meadow.jpg",
    title: { en: "Summer Meadow", da: "Sommereng" },
    medium: { en: "Oil on panel", da: "Olie på plade" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "landscape",
    category: "painting",
  },
  {
    slug: "evening-landscape",
    number: 18,
    image: "/art/18-evening-landscape.jpg",
    title: { en: "Evening Landscape", da: "Aftenlandskab" },
    medium: { en: "Oil on linen", da: "Olie på lærred" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "landscape",
    category: "painting",
  },
  {
    slug: "landscape-study",
    number: 19,
    image: "/art/19-landscape-study.jpg",
    title: { en: "Landscape Study", da: "Landskabsstudie" },
    medium: { en: "Oil on paper", da: "Olie på papir" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "landscape",
    category: "painting",
  },
  {
    slug: "girl-and-oak",
    number: 20,
    image: "/art/20-girl-and-oak.jpg",
    title: { en: "Girl and Oak", da: "Pige og eg" },
    medium: { en: "Ink on paper", da: "Blæk på papir" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "portrait",
    category: "drawing",
  },
  {
    slug: "figures-under-old-tree",
    number: 21,
    image: "/art/21-figures-old-tree.jpg",
    title: {
      en: "Figures under an Old Tree",
      da: "Figurer under et gammelt træ",
    },
    medium: { en: "Ink on paper", da: "Blæk på papir" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "portrait",
    category: "drawing",
  },
  {
    slug: "edge-of-forest",
    number: 22,
    image: "/art/22-edge-of-forest.jpg",
    title: { en: "Edge of Forest", da: "Skovbryn" },
    medium: { en: "Ink on paper", da: "Blæk på papir" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "portrait",
    category: "drawing",
  },
  {
    slug: "willows",
    number: 23,
    image: "/art/23-willows.jpg",
    title: { en: "Willows", da: "Piletræer" },
    medium: { en: "Ink on paper", da: "Blæk på papir" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "landscape",
    category: "drawing",
  },
  {
    slug: "old-tree",
    number: 24,
    image: "/art/24-old-tree.jpg",
    title: { en: "The Old Tree", da: "Det gamle træ" },
    medium: { en: "Ink on paper", da: "Blæk på papir" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "landscape",
    category: "drawing",
  },
  {
    slug: "pastoral-scene",
    number: 25,
    image: "/art/25-pastoral-scene.jpg",
    title: { en: "Pastoral Scene", da: "Pastoralt motiv" },
    medium: { en: "Ink on paper", da: "Blæk på papir" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "square",
    category: "drawing",
  },
  {
    slug: "el-poppel",
    number: 26,
    image: "/art/26-poplar.jpg",
    title: { en: "El Poppel (Taasinge)", da: "El Poppel (Taasinge)" },
    medium: { en: "Ink on paper", da: "Blæk på papir" },
    year: "2023",
    dimensions: null,
    available: true,
    orientation: "portrait",
    category: "drawing",
  },
  {
    slug: "portrait-young-woman",
    number: 27,
    image: "/art/27-portrait-young-woman.jpg",
    title: {
      en: "Portrait of a Young Woman",
      da: "Portræt af en ung kvinde",
    },
    medium: { en: "Pencil on paper", da: "Blyant på papir" },
    year: "2024",
    dimensions: null,
    available: true,
    orientation: "portrait",
    category: "drawing",
  },
  {
    slug: "portrait-study-man",
    number: 28,
    image: "/art/28-portrait-study-man.jpg",
    title: { en: "Portrait Study", da: "Portrætstudie" },
    medium: { en: "Ink on paper", da: "Blæk på papir" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "portrait",
    category: "drawing",
  },
  {
    slug: "young-woman-profile",
    number: 29,
    image: "/art/29-young-woman-profile.jpg",
    title: {
      en: "Young Woman in Profile",
      da: "Ung kvinde i profil",
    },
    medium: { en: "Ink on paper", da: "Blæk på papir" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "portrait",
    category: "drawing",
  },
  {
    slug: "self-portrait-study",
    number: 30,
    image: "/art/30-self-portrait-study.jpg",
    title: { en: "Self-Portrait Study", da: "Selvportrætstudie" },
    medium: { en: "Ink on paper", da: "Blæk på papir" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "square",
    category: "drawing",
  },
  {
    slug: "jackal-skull",
    number: 31,
    image: "/art/31-jackal-skull.jpg",
    title: { en: "Jackal Skull", da: "Sjakalkranie" },
    medium: { en: "Pencil on paper", da: "Blyant på papir" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "landscape",
    category: "drawing",
  },
  {
    slug: "memento-mori",
    number: 32,
    image: "/art/32-memento-mori.jpg",
    title: {
      en: "Memento Mori",
      da: "Memento mori",
    },
    medium: { en: "Pencil on paper", da: "Blyant på papir" },
    year: null,
    dimensions: null,
    available: true,
    orientation: "landscape",
    category: "drawing",
  },
];

export function getArtwork(slug: string): Artwork | undefined {
  return artworks.find((a) => a.slug === slug);
}

export const paintings = artworks.filter((a) => a.category === "painting");
export const drawings = artworks.filter((a) => a.category === "drawing");
