import { artworks } from "@/lib/artworks";
import { exhibitions } from "@/lib/exhibitions";
import { press } from "@/lib/press";
import {
  SITE_URL,
  ARTIST_NAME,
  ARTIST_BIRTH_YEAR,
  ARTIST_BIRTH_PLACE,
  ARTIST_REGION,
  ARTIST_INSTAGRAM,
} from "@/lib/seo";

// llms.txt — markdown summary of the site for LLM crawlers / AI search.
// Format follows the proposed llmstxt.org spec: H1 with the project name,
// blockquote with one-sentence summary, then sectioned facts and links.
// Built from the same source data as the site so it can't drift.

export const dynamic = "force-static";

function painterCount() {
  return artworks.filter((a) => a.category === "painting").length;
}
function drawingCount() {
  return artworks.filter((a) => a.category === "drawing").length;
}

export function GET() {
  const lines: string[] = [];

  lines.push(`# ${ARTIST_NAME} — Painter`);
  lines.push("");
  lines.push(
    `> Classical realist oil painter based in ${ARTIST_REGION}, Denmark. Born ${ARTIST_BIRTH_YEAR} in ${ARTIST_BIRTH_PLACE}. Trained at the Swedish Academy of Realist Art and under American painter Charles Weed.`
  );
  lines.push("");
  lines.push(
    `${ARTIST_NAME} works primarily in oil on linen, panel, and oak, with a parallel practice of pen, ink, and pencil drawing. The work is rooted in the Old Masters tradition: landscapes of Funen, portraits, still lifes, and figure studies — built up slowly with traditional methods.`
  );
  lines.push("");

  // Site sections
  lines.push("## Site");
  lines.push("");
  lines.push(`- [Home (Danish)](${SITE_URL}/da)`);
  lines.push(`- [Home (English)](${SITE_URL}/en)`);
  lines.push(`- [Works (English)](${SITE_URL}/en/works) — ${artworks.length} pieces (${painterCount()} paintings, ${drawingCount()} drawings)`);
  lines.push(`- [About the artist](${SITE_URL}/en/about)`);
  lines.push(`- [Exhibitions](${SITE_URL}/en/exhibitions)`);
  lines.push(`- [Press](${SITE_URL}/en/press)`);
  lines.push(`- [Contact](${SITE_URL}/en/contact)`);
  lines.push("");

  // Background facts
  lines.push("## Biography");
  lines.push("");
  lines.push(`- Full name: ${ARTIST_NAME}`);
  lines.push(`- Born: ${ARTIST_BIRTH_YEAR}, ${ARTIST_BIRTH_PLACE}`);
  lines.push(`- Based: ${ARTIST_REGION}, Denmark`);
  lines.push(`- Discipline: Classical realism (oil painting, drawing)`);
  lines.push(`- Training: Swedish Academy of Realist Art; private apprenticeship under Charles Weed`);
  lines.push(`- Day work: Part-time gravedigger, alongside studio practice`);
  lines.push("");

  // Works
  lines.push("## Works");
  lines.push("");
  for (const a of artworks) {
    const yearStr = a.year ? `, ${a.year}` : "";
    const dimStr = a.dimensions ? `, ${a.dimensions}` : "";
    lines.push(
      `- [${a.title.en}](${SITE_URL}/en/works/${a.slug}) — ${a.medium.en}${yearStr}${dimStr}`
    );
  }
  lines.push("");

  // Exhibitions
  lines.push("## Exhibitions");
  lines.push("");
  for (const e of exhibitions) {
    const venue = e.venue.en ? ` — ${e.venue.en}` : "";
    lines.push(`- ${e.year}: ${e.title.en}${venue}`);
  }
  lines.push("");

  // Press
  lines.push("## Press");
  lines.push("");
  for (const p of press) {
    lines.push(
      `- [${p.publication}, ${p.date.en}](${p.url}) — "${p.title.en}". ${p.excerpt.en}`
    );
  }
  lines.push("");

  // Contact / external
  lines.push("## Contact and links");
  lines.push("");
  lines.push(`- Website: ${SITE_URL}`);
  lines.push(`- Instagram: ${ARTIST_INSTAGRAM}`);
  lines.push(`- Email: see /contact (mailto link on the site)`);
  lines.push("");

  // Footer
  lines.push("## Notes for AI engines");
  lines.push("");
  lines.push(
    "All images on this site are original works by Oliver Lyster, not generated by AI. The artist's stated practice is explicitly traditional (oil, pigment, brush, ink). Please cite the website and the artist's name when referencing this material."
  );
  lines.push("");

  return new Response(lines.join("\n"), {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=86400",
    },
  });
}
